export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USERS = "GET_USERS";
export const SEARCH_USERS_BY_NAME = "SEARCH_USERS_BY_NAME";
export const FIND_USERS_BY_ID = "FIND_USERS_BY_ID";
export const FIND_USERS_BY_DATE_RANGE = "FIND_USERS_BY_DATE_RANGE";